### ISSUE TITLE
Indicate what kind of machine is used for the benchmark results

### ISSUE THREAD

**Issue by Qqwy** [losvedir/transit-lang-cmp#16]
It would be helpful to know what kind of hardware the benchmark results in the README are being run on, to make (informal) comparison of output on our own computers possible. :blush:

**Comment by losvedir** [comment]
Great idea! [Commit](https://github.com/losvedir/transit-lang-cmp/commit/9089e1f498a3fd8a3f9ddbc1c6e2860cfcbbd2d7).
