### ISSUE TITLE
Enable lto for rust

### ISSUE THREAD

**Issue by pbspbsingh** [losvedir/transit-lang-cmp#2]
Please enable link time optimization in rust's Cargo.toml

```
[profile.release]
lto = true
```

**Comment by losvedir** [comment]
[Done!](https://github.com/losvedir/transit-lang-cmp/commit/faa9ab7120b8a36452527094a18b3eb14f9d4ee8) Got a nice little boost in all the stats, thanks for the suggestion!

The compile times weren't affected too much for me, so I imagine this is something most projects would leave on, at least initially, and only turn off once they got to a certain size? It seems "fair" or "realistic" to me to enable it here, and it's not just something for juicing the stats.

**Comment by pbspbsingh** [comment]
Yeah totally, I keep lto on (release profile only) for all my rust project, it also helps reduce the binary size.
